; generated by SuperSlicer 2.3.56 on 2021-09-26 at 03:12:48 UTC

; 

; external perimeters extrusion width = 0.52mm
; perimeters extrusion width = 0.57mm
; infill extrusion width = 0.55mm
; solid infill extrusion width = 0.57mm
; top infill extrusion width = 0.55mm
; support material extrusion width = 0.50mm
; first layer extrusion width = 0.70mm

; external perimeters extrusion width = 0.52mm
; perimeters extrusion width = 0.57mm
; infill extrusion width = 0.55mm
; solid infill extrusion width = 0.57mm
; top infill extrusion width = 0.55mm
; support material extrusion width = 0.50mm
; first layer extrusion width = 0.70mm

; external perimeters extrusion width = 0.52mm
; perimeters extrusion width = 0.57mm
; infill extrusion width = 0.55mm
; solid infill extrusion width = 0.57mm
; top infill extrusion width = 0.55mm
; support material extrusion width = 0.50mm
; first layer extrusion width = 0.70mm

; object:{"name":"patch_bed_leveling","id":"patch_bed_leveling id:0 copy 0","object_center":[-93.549999,93.549999,0.000000],"boundingbox_center":[-93.549999,93.549999,1.858172],"boundingbox_size":[27.783124,27.783124,3.716344]}
; object:{"name":"patch_bed_leveling","id":"patch_bed_leveling id:1 copy 0","object_center":[93.549999,-93.549999,0.000000],"boundingbox_center":[93.549999,-93.549999,1.858172],"boundingbox_size":[27.783124,27.783124,3.716344]}
; object:{"name":"patch_bed_leveling","id":"patch_bed_leveling id:2 copy 0","object_center":[0.000000,0.000000,0.000000],"boundingbox_center":[0.000000,0.000000,1.858172],"boundingbox_size":[27.783124,27.783124,3.716344]}
; object:{"name":"patch_bed_leveling","id":"patch_bed_leveling id:3 copy 0","object_center":[-93.549999,-93.549999,0.000000],"boundingbox_center":[-93.549999,-93.549999,1.858172],"boundingbox_size":[27.783124,27.783124,3.716344]}
; object:{"name":"patch_bed_leveling","id":"patch_bed_leveling id:4 copy 0","object_center":[93.549999,93.549999,0.000000],"boundingbox_center":[93.549999,93.549999,1.858172],"boundingbox_size":[27.783124,27.783124,3.716344]}
; Total objects to print: 5
M486 T5
; plater:{"center":[0.000000,0.000000,0.000000],"boundingbox_center":[0.000000,0.000000,1.858172],"boundingbox_size":[214.883123,214.883123,3.716344]}

G10 P0 R190 ; sets the standby temperature
G10 P0 S200 ; set temperature
;TYPE:Custom
; Call the print start macro and pass in first layer temp and bed temp.
; TODO: when we are using the right-side extruder, start there instead of running this against the wrong one
M140 S0
M568 P0 R0 S0 A0
M98 P"0:/macros/sys/start_print.g" T200 B60; call print start macro (handles loading filament, priming nozzle, etc.
M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
G10 P0 S200 ; set temperature
M116 ; wait for temperature to be reached
;LAYER_CHANGE
;Z:0.375
;HEIGHT:0.375
G1 Z0.375000 F12000
G1 E-2.00000 F2400
G1 X-84.721 Y84.727 F12000
G1 E0.00000 F2400
;TYPE:Skirt
;WIDTH:0.55
G1 F1800
G1 X-75.134 Y94.313 E1.03946
G1 X-74.239 Y95.520 E1.15458
G1 X-73.658 Y96.911 E1.27017
G1 X-73.428 Y98.363 E1.38294
G1 X-73.547 Y99.836 E1.49618
G1 X-74.006 Y101.233 E1.60895
G1 X-74.779 Y102.484 E1.72172
G1 X-84.298 Y112.050 E2.75636
G1 X-85.468 Y112.891 E2.86678
G1 X-86.805 Y113.442 E2.97767
G1 X-88.332 Y113.674 E3.09607
G1 X-89.863 Y113.525 E3.21401
G1 X-91.311 Y113.005 E3.33194
G1 X-92.587 Y112.147 E3.44988
G1 X-111.261 Y93.492 E5.47353
G1 X-112.158 Y92.280 E5.58912
G1 X-112.737 Y90.895 E5.70424
G1 X-112.969 Y89.355 E5.82358
G1 X-112.814 Y87.813 E5.94245
G1 X-112.283 Y86.356 E6.06133
G1 X-111.405 Y85.071 E6.18067
G1 X-101.820 Y75.518 E7.21815
G1 X-100.943 Y74.923 E7.29940
G1 X-99.978 Y74.486 E7.38064
G1 X-98.952 Y74.219 E7.46189
G1 X-97.890 Y74.129 E7.54361
G1 X-96.719 Y74.241 E7.63381
G1 X-95.596 Y74.570 E7.72354
G1 X-94.553 Y75.102 E7.81326
G1 X-93.629 Y75.819 E7.90299
G1 X-84.774 Y84.674 E8.86301
; INIT printing object patch_bed_leveling id:0 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-89.428 Y89.328 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.7
G1 F1800
G1 X-80.153 Y98.603 E1.32688
G1 X-88.497 Y106.947 E2.52056
G1 X-106.241 Y89.203 E5.05904
G1 X-97.897 Y80.859 E6.25272
G1 X-89.481 Y89.275 E7.45674
G1 X-89.558 Y89.811 F12000
G92 E0
G1 E-2.00000 F2400
G1 X-88.061 Y106.247 F12000
G1 E0.00000 F2400
;TYPE:Solid infill
;WIDTH:0.712527
G1 F1200
G1 X-105.345 Y88.963 E2.51693
G1 X-104.907 Y88.525 E2.58072
G1 X-87.820 Y105.612 E5.06894
G1 X-87.382 Y105.174 E5.13274
G1 X-104.468 Y88.087 E7.62096
G1 X-104.030 Y87.649 E7.68475
G1 X-86.944 Y104.736 E10.17297
G1 X-86.505 Y104.298 E10.23677
G1 X-103.592 Y87.211 E12.72499
G1 X-103.154 Y86.773 E12.78878
G1 X-86.067 Y103.860 E15.27700
G1 X-85.629 Y103.422 E15.34080
G1 X-102.716 Y86.335 E17.82902
G1 X-102.278 Y85.897 E17.89281
G1 X-85.191 Y102.983 E20.38104
G1 X-84.753 Y102.545 E20.44483
G1 X-101.840 Y85.458 E22.93305
G1 X-101.402 Y85.020 E22.99684
G1 X-84.315 Y102.107 E25.48507
G1 X-83.877 Y101.669 E25.54886
G1 X-100.964 Y84.582 E28.03708
G1 X-100.526 Y84.144 E28.10087
G1 X-83.439 Y101.231 E30.58910
G1 X-83.001 Y100.793 E30.65289
G1 X-100.088 Y83.706 E33.14111
G1 X-99.650 Y83.268 E33.20490
G1 X-82.563 Y100.355 E35.69313
G1 X-82.125 Y99.917 E35.75692
G1 X-99.212 Y82.830 E38.24514
G1 X-98.774 Y82.392 E38.30893
G1 X-81.687 Y99.479 E40.79716
G1 X-81.249 Y99.041 E40.86095
G1 X-98.336 Y81.954 E43.34917
G1 X-97.897 Y81.516 E43.41297
G1 X-80.613 Y98.800 E45.92990
G92 E0
G1 E-2.00000 F2400
G1 X-105.740 Y89.140 F12000
G1 E0.00000 F2400
;TYPE:Gap fill
;WIDTH:0.258087
G1 F1200
G1 X-105.678 Y89.203 E0.00257
G1 X-97.087 Y97.793 E0.35489
G1 X-88.497 Y106.383 E0.70721
G1 X-88.434 Y106.446 E0.70979
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:0.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z0.575000 F12000
G10 P0 S190 ; set temperature
M140 S55 ; set bed temperature
; INIT printing object patch_bed_leveling id:0 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-105.794 Y89.777 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.52
G1 F1800
G1 X-106.447 Y89.124 E0.03836
G1 X-97.976 Y80.653 E0.53609
G1 X-97.323 Y81.306 E0.57445
G1 X-105.741 Y89.724 E1.06907
G1 X-105.923 Y89.294 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:0.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z0.775000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-105.795 Y89.670
G1 F600
G1 X-105.848 Y89.723 E1.07218
G1 X-106.501 Y89.070 E1.11055
G1 X-98.030 Y80.599 E1.60828
G1 X-97.377 Y81.252 E1.64664
G1 X-105.742 Y89.617 E2.13814
G1 X-105.868 Y89.650 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
M106 S255
;LAYER_CHANGE
;Z:0.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z0.975000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-105.797 Y89.562
G1 F600
G1 X-105.903 Y89.668 E2.14437
G1 X-106.556 Y89.015 E2.18273
G1 X-98.085 Y80.544 E2.68046
G1 X-97.432 Y81.197 E2.71883
G1 X-105.744 Y89.509 E3.20721
G1 X-105.942 Y89.523 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:1.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z1.175000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-105.798 Y89.455
G1 F600
G1 X-105.957 Y89.614 E3.21656
G1 X-106.610 Y88.961 E3.25492
G1 X-98.139 Y80.490 E3.75265
G1 X-97.486 Y81.143 E3.79101
G1 X-105.745 Y89.402 E4.27628
G1 X-106.015 Y89.397 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:1.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z1.375000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.012 Y89.559
G1 F600
G1 X-106.665 Y88.907 E4.31464
G1 X-98.193 Y80.435 E4.81237
G1 X-97.540 Y81.088 E4.85074
G1 X-105.959 Y89.506 E5.34535
G1 X-106.141 Y89.077 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:1.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z1.575000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.013 Y89.452
G1 F600
G1 X-106.066 Y89.505 E5.34847
G1 X-106.719 Y88.852 E5.38683
G1 X-98.248 Y80.381 E5.88456
G1 X-97.595 Y81.034 E5.92292
G1 X-105.960 Y89.399 E6.41442
G1 X-106.085 Y89.433 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:1.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z1.775000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.014 Y89.345
G1 F600
G1 X-106.120 Y89.451 E6.42065
G1 X-106.773 Y88.798 E6.45902
G1 X-98.302 Y80.327 E6.95675
G1 X-97.649 Y80.980 E6.99511
G1 X-105.961 Y89.292 E7.48349
G1 X-106.159 Y89.306 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:1.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z1.975000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.016 Y89.237
G1 F600
G1 X-106.175 Y89.396 E7.49284
G1 X-106.828 Y88.743 E7.53121
G1 X-98.357 Y80.272 E8.02894
G1 X-97.704 Y80.925 E8.06730
G1 X-105.963 Y89.184 E8.55257
G1 X-106.233 Y89.179 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:2.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z2.175000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.229 Y89.342
G1 F600
G1 X-106.882 Y88.689 E8.59093
G1 X-98.411 Y80.218 E9.08866
G1 X-97.758 Y80.871 E9.12703
G1 X-106.176 Y89.289 E9.62164
G1 X-106.359 Y88.859 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:2.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z2.375000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.231 Y89.234
G1 F600
G1 X-106.284 Y89.287 E9.62476
G1 X-106.937 Y88.634 E9.66312
G1 X-98.466 Y80.163 E10.16085
G1 X-97.813 Y80.816 E10.19922
G1 X-106.178 Y89.181 E10.69071
G1 X-106.303 Y89.215 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:2.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z2.575000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.232 Y89.127
G1 F600
G1 X-106.338 Y89.233 E10.69695
G1 X-106.991 Y88.580 E10.73531
G1 X-98.520 Y80.109 E11.23304
G1 X-97.867 Y80.762 E11.27141
G1 X-106.179 Y89.074 E11.75979
G1 X-106.377 Y89.088 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:2.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z2.775000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.234 Y89.019
G1 F600
G1 X-106.393 Y89.178 E11.76914
G1 X-107.046 Y88.526 E11.80750
G1 X-98.574 Y80.054 E12.30523
G1 X-97.922 Y80.707 E12.34360
G1 X-106.181 Y88.966 E12.82887
G1 X-106.451 Y88.961 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:2.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z2.975000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.447 Y89.124
G1 F600
G1 X-106.995 Y88.576 E12.86108
G1 X-98.524 Y80.105 E13.35881
G1 X-97.976 Y80.653 E13.39102
G1 X-106.394 Y89.071 E13.88564
G1 X-106.576 Y88.641 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:3.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z3.175000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.502 Y89.070
G1 F600
G1 X-106.832 Y88.739 E13.90506
G1 X-98.361 Y80.268 E14.40279
G1 X-98.030 Y80.598 E14.42221
G1 X-106.448 Y89.017 E14.91683
G1 X-106.622 Y88.618 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:3.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z3.375000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-106.503 Y88.962
G1 F600
G1 X-106.556 Y89.015 E14.91994
G1 X-106.669 Y88.902 E14.92657
G1 X-98.198 Y80.431 E15.42430
G1 X-98.085 Y80.544 E15.43093
G1 X-106.450 Y88.909 E15.92243
G1 X-106.575 Y88.943 F12000
; INIT stop printing object patch_bed_leveling id:0 copy 0
;LAYER_CHANGE
;Z:3.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 Z3.575000 F12000
; INIT printing object patch_bed_leveling id:0 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:0 copy 0
M486 S0
G1 X-97.903 Y80.358 F12000
G1 E0.00000 F2400
;TYPE:Thin wall
;WIDTH:0.1
G1 F600
G1 X-97.929 Y80.385 E0.00014
;WIDTH:0.2

G1 X-97.955 Y80.411 E0.00057
;WIDTH:0.3

G1 X-97.982 Y80.437 E0.00132
;WIDTH:0.4

G1 X-98.008 Y80.463 E0.00239
;WIDTH:0.5

G1 X-98.034 Y80.490 E0.00387
G1 X-106.610 Y89.066 E0.48657
G1 X-106.624 Y89.079 E0.48731
;WIDTH:0.4

G1 X-106.650 Y89.105 E0.48854
;WIDTH:0.3

G1 X-106.676 Y89.131 E0.48945
;WIDTH:0.2

G1 X-106.702 Y89.158 E0.49004
;WIDTH:0.1

G1 X-106.729 Y89.184 E0.49031
; INIT stop printing object patch_bed_leveling id:0 copy 0
G92 E0
G1 E-2.00000 F2400
G92 E0
; stop printing object patch_bed_leveling id:0 copy 0
M486 S-1
G1 X93.550 Y-93.550 F12000
M140 S60 ; set bed temperature
G10 P0 S200 ; set temperature
M107
;LAYER_CHANGE
;Z:0.375
;HEIGHT:0.375
G1 Z0.375000 F12000
G1 X84.732 Y-84.724
G1 E2.00000 F2400
;TYPE:Skirt
;WIDTH:0.55
G1 F1800
G1 X75.839 Y-93.608 E2.96377
G1 X74.942 Y-94.820 E3.07935
G1 X74.363 Y-96.205 E3.19447
G1 X74.131 Y-97.744 E3.31381
G1 X74.286 Y-99.287 E3.43269
G1 X74.817 Y-100.744 E3.55156
G1 X75.695 Y-102.029 E3.67090
G1 X85.280 Y-111.582 E4.70838
G1 X86.157 Y-112.177 E4.78963
G1 X87.122 Y-112.614 E4.87088
G1 X88.148 Y-112.881 E4.95213
G1 X89.210 Y-112.971 E5.03384
G1 X90.375 Y-112.860 E5.12357
G1 X91.499 Y-112.533 E5.21330
G1 X92.547 Y-111.998 E5.30350
G1 X93.471 Y-111.281 E5.39322
G1 X111.966 Y-92.787 E7.39846
G1 X112.861 Y-91.580 E7.51358
G1 X113.442 Y-90.189 E7.62916
G1 X113.672 Y-88.737 E7.74193
G1 X113.553 Y-87.264 E7.85517
G1 X113.094 Y-85.867 E7.96794
G1 X112.321 Y-84.616 E8.08071
G1 X102.802 Y-75.050 E9.11535
G1 X101.627 Y-74.206 E9.22624
G1 X100.295 Y-73.658 E9.33666
G1 X98.774 Y-73.426 E9.45460
G1 X97.243 Y-73.574 E9.57253
G1 X95.795 Y-74.092 E9.69047
G1 X94.513 Y-74.953 E9.80887
G1 X84.785 Y-84.671 E10.86301
; INIT printing object patch_bed_leveling id:1 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X89.435 Y-89.321 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.7
G1 F1800
G1 X80.859 Y-97.897 E1.22700
G1 X89.203 Y-106.241 E2.42067
G1 X106.947 Y-88.497 E4.95916
G1 X98.603 Y-80.153 E6.15284
G1 X89.488 Y-89.268 E7.45674
G1 X89.565 Y-89.804 F12000
G92 E0
G1 E-2.00000 F2400
G1 X106.487 Y-88.300 F12000
G1 E0.00000 F2400
;TYPE:Solid infill
;WIDTH:0.712527
G1 F1200
G1 X89.203 Y-105.584 E2.51693
G1 X88.764 Y-105.146 E2.58072
G1 X105.851 Y-88.059 E5.06894
G1 X105.413 Y-87.621 E5.13274
G1 X88.326 Y-104.708 E7.62096
G1 X87.888 Y-104.270 E7.68475
G1 X104.975 Y-87.183 E10.17297
G1 X104.537 Y-86.745 E10.23677
G1 X87.450 Y-103.832 E12.72499
G1 X87.012 Y-103.394 E12.78878
G1 X104.099 Y-86.307 E15.27700
G1 X103.661 Y-85.869 E15.34080
G1 X86.574 Y-102.956 E17.82902
G1 X86.136 Y-102.518 E17.89281
G1 X103.223 Y-85.431 E20.38104
G1 X102.785 Y-84.993 E20.44483
G1 X85.698 Y-102.080 E22.93305
G1 X85.260 Y-101.642 E22.99684
G1 X102.347 Y-84.555 E25.48507
G1 X101.909 Y-84.117 E25.54886
G1 X84.822 Y-101.203 E28.03708
G1 X84.384 Y-100.765 E28.10087
G1 X101.471 Y-83.678 E30.58910
G1 X101.033 Y-83.240 E30.65289
G1 X83.946 Y-100.327 E33.14111
G1 X83.508 Y-99.889 E33.20490
G1 X100.595 Y-82.802 E35.69313
G1 X100.156 Y-82.364 E35.75692
G1 X83.070 Y-99.451 E38.24514
G1 X82.631 Y-99.013 E38.30893
G1 X99.718 Y-81.926 E40.79716
G1 X99.280 Y-81.488 E40.86095
G1 X82.193 Y-98.575 E43.34917
G1 X81.755 Y-98.137 E43.41297
G1 X99.039 Y-80.853 E45.92990
G92 E0
G1 E-2.00000 F2400
G1 X81.360 Y-97.960 F12000
G1 E0.00000 F2400
;TYPE:Gap fill
;WIDTH:0.258088
G1 F1200
G1 X81.391 Y-97.929 E0.00129
G1 X81.422 Y-97.897 E0.00257
G1 X90.013 Y-89.307 E0.35490
G1 X98.603 Y-80.717 E0.70722
G1 X98.666 Y-80.654 E0.70979
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:0.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z0.575000 F12000
G10 P0 S190 ; set temperature
M140 S55 ; set bed temperature
; INIT printing object patch_bed_leveling id:1 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X81.306 Y-97.323 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.52
G1 F1800
G1 X80.653 Y-97.976 E0.03836
G1 X89.124 Y-106.447 E0.53609
G1 X89.777 Y-105.794 E0.57445
G1 X81.359 Y-97.376 E1.06907
G1 X81.177 Y-97.806 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:0.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z0.775000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X81.305 Y-97.430
G1 F600
G1 X81.252 Y-97.377 E1.07218
G1 X80.599 Y-98.030 E1.11055
G1 X89.070 Y-106.501 E1.60828
G1 X89.723 Y-105.848 E1.64664
G1 X81.358 Y-97.483 E2.13814
G1 X81.232 Y-97.450 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
M106 S255
;LAYER_CHANGE
;Z:0.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z0.975000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X81.303 Y-97.538
G1 F600
G1 X81.197 Y-97.432 E2.14437
G1 X80.544 Y-98.085 E2.18273
G1 X89.015 Y-106.556 E2.68046
G1 X89.668 Y-105.903 E2.71883
G1 X81.356 Y-97.591 E3.20721
G1 X81.158 Y-97.577 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:1.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z1.175000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X81.302 Y-97.645
G1 F600
G1 X81.143 Y-97.486 E3.21656
G1 X80.490 Y-98.139 E3.25492
G1 X88.961 Y-106.610 E3.75265
G1 X89.614 Y-105.957 E3.79101
G1 X81.355 Y-97.698 E4.27628
G1 X81.085 Y-97.703 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:1.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z1.375000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X81.088 Y-97.540
G1 F600
G1 X80.435 Y-98.193 E4.31464
G1 X88.907 Y-106.665 E4.81237
G1 X89.559 Y-106.012 E4.85074
G1 X81.141 Y-97.594 E5.34535
G1 X80.959 Y-98.023 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:1.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z1.575000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X81.087 Y-97.648
G1 F600
G1 X81.034 Y-97.595 E5.34847
G1 X80.381 Y-98.248 E5.38683
G1 X88.852 Y-106.719 E5.88456
G1 X89.505 Y-106.066 E5.92292
G1 X81.140 Y-97.701 E6.41442
G1 X81.015 Y-97.667 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:1.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z1.775000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X81.086 Y-97.755
G1 F600
G1 X80.980 Y-97.649 E6.42065
G1 X80.327 Y-98.302 E6.45902
G1 X88.798 Y-106.773 E6.95675
G1 X89.451 Y-106.120 E6.99511
G1 X81.139 Y-97.808 E7.48349
G1 X80.941 Y-97.794 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:1.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z1.975000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X81.084 Y-97.863
G1 F600
G1 X80.925 Y-97.704 E7.49284
G1 X80.272 Y-98.357 E7.53121
G1 X88.743 Y-106.828 E8.02894
G1 X89.396 Y-106.175 E8.06730
G1 X81.137 Y-97.916 E8.55257
G1 X80.867 Y-97.921 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:2.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z2.175000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X80.871 Y-97.758
G1 F600
G1 X80.218 Y-98.411 E8.59093
G1 X88.689 Y-106.882 E9.08866
G1 X89.342 Y-106.229 E9.12703
G1 X80.924 Y-97.811 E9.62164
G1 X80.741 Y-98.241 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:2.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z2.375000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X80.869 Y-97.866
G1 F600
G1 X80.816 Y-97.813 E9.62476
G1 X80.163 Y-98.466 E9.66312
G1 X88.634 Y-106.937 E10.16085
G1 X89.287 Y-106.284 E10.19922
G1 X80.922 Y-97.919 E10.69071
G1 X80.797 Y-97.885 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:2.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z2.575000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X80.868 Y-97.973
G1 F600
G1 X80.762 Y-97.867 E10.69695
G1 X80.109 Y-98.520 E10.73531
G1 X88.580 Y-106.991 E11.23304
G1 X89.233 Y-106.338 E11.27141
G1 X80.921 Y-98.026 E11.75979
G1 X80.723 Y-98.012 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:2.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z2.775000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X80.866 Y-98.081
G1 F600
G1 X80.707 Y-97.922 E11.76914
G1 X80.054 Y-98.574 E11.80750
G1 X88.526 Y-107.046 E12.30523
G1 X89.178 Y-106.393 E12.34360
G1 X80.919 Y-98.134 E12.82887
G1 X80.649 Y-98.139 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:2.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z2.975000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X80.653 Y-97.976
G1 F600
G1 X80.105 Y-98.524 E12.86108
G1 X88.576 Y-106.995 E13.35881
G1 X89.124 Y-106.447 E13.39102
G1 X80.706 Y-98.029 E13.88564
G1 X80.523 Y-98.459 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:3.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z3.175000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X80.598 Y-98.030
G1 F600
G1 X80.268 Y-98.361 E13.90506
G1 X88.739 Y-106.832 E14.40279
G1 X89.070 Y-106.502 E14.42221
G1 X80.652 Y-98.083 E14.91683
G1 X80.477 Y-98.482 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:3.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z3.375000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X80.597 Y-98.138
G1 F600
G1 X80.544 Y-98.085 E14.91994
G1 X80.431 Y-98.198 E14.92657
G1 X88.902 Y-106.669 E15.42430
G1 X89.015 Y-106.556 E15.43093
G1 X80.650 Y-98.191 E15.92243
G1 X80.525 Y-98.157 F12000
; INIT stop printing object patch_bed_leveling id:1 copy 0
;LAYER_CHANGE
;Z:3.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 Z3.575000 F12000
; INIT printing object patch_bed_leveling id:1 copy 0
; printing object patch_bed_leveling id:1 copy 0
M486 S1
G1 X80.358 Y-97.903
;TYPE:Thin wall
;WIDTH:0.1
G1 F600
G1 X80.385 Y-97.929 E15.92257
;WIDTH:0.2

G1 X80.411 Y-97.955 E15.92300
;WIDTH:0.3

G1 X80.437 Y-97.982 E15.92375
;WIDTH:0.4

G1 X80.463 Y-98.008 E15.92482
;WIDTH:0.5

G1 X80.490 Y-98.034 E15.92630
G1 X89.066 Y-106.610 E16.40899
G1 X89.079 Y-106.624 E16.40973
;WIDTH:0.4

G1 X89.105 Y-106.650 E16.41097
;WIDTH:0.3

G1 X89.131 Y-106.676 E16.41188
;WIDTH:0.2

G1 X89.158 Y-106.702 E16.41247
;WIDTH:0.1

G1 X89.184 Y-106.729 E16.41274
; INIT stop printing object patch_bed_leveling id:1 copy 0
G92 E0
G1 E-2.00000 F2400
G92 E0
; stop printing object patch_bed_leveling id:1 copy 0
M486 S-1
G1 X0.000 Y0.000 F12000
M140 S60 ; set bed temperature
G10 P0 S200 ; set temperature
M107
;LAYER_CHANGE
;Z:0.375
;HEIGHT:0.375
G1 Z0.375000 F12000
G1 X-8.818 Y8.826
G1 E2.00000 F2400
;TYPE:Skirt
;WIDTH:0.55
G1 F1800
G1 X-17.711 Y-0.058 E2.96377
G1 X-18.608 Y-1.270 E3.07935
G1 X-19.187 Y-2.655 E3.19447
G1 X-19.419 Y-4.194 E3.31381
G1 X-19.264 Y-5.737 E3.43269
G1 X-18.730 Y-7.200 E3.55203
G1 X-17.855 Y-8.479 E3.67090
G1 X-8.270 Y-18.032 E4.70838
G1 X-7.393 Y-18.627 E4.78963
G1 X-6.428 Y-19.064 E4.87088
G1 X-5.402 Y-19.331 E4.95213
G1 X-4.340 Y-19.421 E5.03384
G1 X-3.169 Y-19.309 E5.12404
G1 X-2.046 Y-18.980 E5.21377
G1 X-1.003 Y-18.448 E5.30350
G1 X-0.079 Y-17.731 E5.39322
G1 X18.421 Y0.768 E7.39893
G1 X19.314 Y1.975 E7.51405
G1 X19.892 Y3.361 E7.62917
G1 X20.122 Y4.813 E7.74194
G1 X20.003 Y6.286 E7.85517
G1 X19.544 Y7.683 E7.96794
G1 X18.771 Y8.934 E8.08071
G1 X9.252 Y18.500 E9.11535
G1 X8.082 Y19.341 E9.22578
G1 X6.745 Y19.892 E9.33667
G1 X5.224 Y20.124 E9.45460
G1 X3.693 Y19.976 E9.57253
G1 X2.239 Y19.455 E9.69094
G1 X0.963 Y18.597 E9.80887
G1 X-8.765 Y8.879 E10.86301
; INIT printing object patch_bed_leveling id:2 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-4.115 Y4.229 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.7
G1 F1800
G1 X-12.691 Y-4.347 E1.22700
G1 X-4.347 Y-12.691 E2.42067
G1 X13.397 Y5.053 E4.95916
G1 X5.053 Y13.397 E6.15284
G1 X-4.062 Y4.282 E7.45674
G1 X-3.985 Y3.746 F12000
G92 E0
G1 E-2.00000 F2400
G1 X12.937 Y5.250 F12000
G1 E0.00000 F2400
;TYPE:Solid infill
;WIDTH:0.712527
G1 F1200
G1 X-4.347 Y-12.034 E2.51693
G1 X-4.786 Y-11.596 E2.58072
G1 X12.301 Y5.491 E5.06894
G1 X11.863 Y5.929 E5.13274
G1 X-5.224 Y-11.158 E7.62096
G1 X-5.662 Y-10.720 E7.68475
G1 X11.425 Y6.367 E10.17298
G1 X10.987 Y6.805 E10.23677
G1 X-6.100 Y-10.282 E12.72499
G1 X-6.538 Y-9.844 E12.78878
G1 X10.549 Y7.243 E15.27701
G1 X10.111 Y7.681 E15.34080
G1 X-6.976 Y-9.406 E17.82902
G1 X-7.414 Y-8.968 E17.89281
G1 X9.673 Y8.119 E20.38104
G1 X9.235 Y8.557 E20.44483
G1 X-7.852 Y-8.530 E22.93305
G1 X-8.290 Y-8.092 E22.99685
G1 X8.797 Y8.995 E25.48507
G1 X8.359 Y9.433 E25.54886
G1 X-8.728 Y-7.653 E28.03708
G1 X-9.166 Y-7.215 E28.10088
G1 X7.921 Y9.872 E30.58910
G1 X7.483 Y10.310 E30.65289
G1 X-9.604 Y-6.777 E33.14112
G1 X-10.042 Y-6.339 E33.20491
G1 X7.045 Y10.748 E35.69313
G1 X6.606 Y11.186 E35.75692
G1 X-10.480 Y-5.901 E38.24515
G1 X-10.918 Y-5.463 E38.30894
G1 X6.168 Y11.624 E40.79716
G1 X5.730 Y12.062 E40.86095
G1 X-11.357 Y-5.025 E43.34918
G1 X-11.795 Y-4.587 E43.41297
G1 X5.489 Y12.697 E45.92990
G92 E0
G1 E-2.00000 F2400
G1 X-12.190 Y-4.410 F12000
G1 E0.00000 F2400
;TYPE:Gap fill
;WIDTH:0.258091
G1 F1200
G1 X-12.128 Y-4.347 E0.00257
G1 X5.053 Y12.833 E0.70723
G1 X5.084 Y12.864 E0.70852
G1 X5.116 Y12.896 E0.70981
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:0.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z0.575000 F12000
G10 P0 S190 ; set temperature
M140 S55 ; set bed temperature
; INIT printing object patch_bed_leveling id:2 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.244 Y-3.773 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.52
G1 F1800
G1 X-12.897 Y-4.426 E0.03836
G1 X-4.426 Y-12.897 E0.53609
G1 X-3.773 Y-12.244 E0.57445
G1 X-12.191 Y-3.826 E1.06907
G1 X-12.373 Y-4.256 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:0.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z0.775000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.245 Y-3.880
G1 F600
G1 X-12.298 Y-3.827 E1.07218
G1 X-12.951 Y-4.480 E1.11055
G1 X-4.480 Y-12.951 E1.60828
G1 X-3.827 Y-12.298 E1.64664
G1 X-12.192 Y-3.933 E2.13814
G1 X-12.318 Y-3.900 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
M106 S255
;LAYER_CHANGE
;Z:0.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z0.975000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.247 Y-3.988
G1 F600
G1 X-12.353 Y-3.882 E2.14437
G1 X-13.006 Y-4.535 E2.18273
G1 X-4.535 Y-13.006 E2.68046
G1 X-3.882 Y-12.353 E2.71883
G1 X-12.194 Y-4.041 E3.20721
G1 X-12.392 Y-4.027 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:1.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z1.175000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.248 Y-4.095
G1 F600
G1 X-12.407 Y-3.936 E3.21656
G1 X-13.060 Y-4.589 E3.25492
G1 X-4.589 Y-13.060 E3.75265
G1 X-3.936 Y-12.407 E3.79101
G1 X-12.195 Y-4.148 E4.27628
G1 X-12.465 Y-4.153 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:1.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z1.375000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.462 Y-3.991
G1 F600
G1 X-13.115 Y-4.643 E4.31464
G1 X-4.643 Y-13.115 E4.81237
G1 X-3.991 Y-12.462 E4.85074
G1 X-12.409 Y-4.044 E5.34535
G1 X-12.591 Y-4.473 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:1.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z1.575000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.463 Y-4.098
G1 F600
G1 X-12.516 Y-4.045 E5.34847
G1 X-13.169 Y-4.698 E5.38683
G1 X-4.698 Y-13.169 E5.88456
G1 X-4.045 Y-12.516 E5.92292
G1 X-12.410 Y-4.151 E6.41442
G1 X-12.535 Y-4.117 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:1.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z1.775000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.464 Y-4.205
G1 F600
G1 X-12.570 Y-4.099 E6.42065
G1 X-13.223 Y-4.752 E6.45902
G1 X-4.752 Y-13.223 E6.95675
G1 X-4.099 Y-12.570 E6.99511
G1 X-12.411 Y-4.258 E7.48350
G1 X-12.609 Y-4.244 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:1.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z1.975000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.466 Y-4.313
G1 F600
G1 X-12.625 Y-4.154 E7.49284
G1 X-13.278 Y-4.807 E7.53121
G1 X-4.807 Y-13.278 E8.02894
G1 X-4.154 Y-12.625 E8.06730
G1 X-12.413 Y-4.366 E8.55257
G1 X-12.683 Y-4.371 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:2.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z2.175000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.679 Y-4.208
G1 F600
G1 X-13.332 Y-4.861 E8.59093
G1 X-4.861 Y-13.332 E9.08866
G1 X-4.208 Y-12.679 E9.12703
G1 X-12.626 Y-4.261 E9.62164
G1 X-12.809 Y-4.691 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:2.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z2.375000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.681 Y-4.316
G1 F600
G1 X-12.734 Y-4.263 E9.62476
G1 X-13.387 Y-4.916 E9.66312
G1 X-4.916 Y-13.387 E10.16085
G1 X-4.263 Y-12.734 E10.19922
G1 X-12.628 Y-4.369 E10.69072
G1 X-12.753 Y-4.335 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:2.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z2.575000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.682 Y-4.423
G1 F600
G1 X-12.788 Y-4.317 E10.69695
G1 X-13.441 Y-4.970 E10.73531
G1 X-4.970 Y-13.441 E11.23305
G1 X-4.317 Y-12.788 E11.27141
G1 X-12.629 Y-4.476 E11.75979
G1 X-12.827 Y-4.462 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:2.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z2.775000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.684 Y-4.531
G1 F600
G1 X-12.843 Y-4.372 E11.76914
G1 X-13.496 Y-5.024 E11.80751
G1 X-5.024 Y-13.496 E12.30524
G1 X-4.372 Y-12.843 E12.34360
G1 X-12.631 Y-4.584 E12.82887
G1 X-12.901 Y-4.589 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:2.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z2.975000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.897 Y-4.426
G1 F600
G1 X-13.445 Y-4.974 E12.86108
G1 X-4.974 Y-13.445 E13.35881
G1 X-4.426 Y-12.897 E13.39103
G1 X-12.844 Y-4.479 E13.88564
G1 X-13.026 Y-4.909 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:3.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z3.175000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.952 Y-4.480
G1 F600
G1 X-13.282 Y-4.811 E13.90506
G1 X-4.811 Y-13.282 E14.40280
G1 X-4.480 Y-12.952 E14.42222
G1 X-12.898 Y-4.533 E14.91683
G1 X-13.072 Y-4.932 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:3.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z3.375000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-12.953 Y-4.588
G1 F600
G1 X-13.006 Y-4.535 E14.91995
G1 X-13.119 Y-4.648 E14.92657
G1 X-4.648 Y-13.119 E15.42430
G1 X-4.535 Y-13.006 E15.43093
G1 X-12.900 Y-4.641 E15.92243
G1 X-13.025 Y-4.607 F12000
; INIT stop printing object patch_bed_leveling id:2 copy 0
;LAYER_CHANGE
;Z:3.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 Z3.575000 F12000
; INIT printing object patch_bed_leveling id:2 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:2 copy 0
M486 S2
G1 X-4.353 Y-13.192 F12000
G1 E0.00000 F2400
;TYPE:Thin wall
;WIDTH:0.1
G1 F600
G1 X-4.379 Y-13.165 E0.00014
;WIDTH:0.2

G1 X-4.405 Y-13.139 E0.00057
;WIDTH:0.3

G1 X-4.432 Y-13.113 E0.00132
;WIDTH:0.4

G1 X-4.458 Y-13.087 E0.00239
;WIDTH:0.5

G1 X-4.484 Y-13.060 E0.00387
G1 X-13.060 Y-4.484 E0.48657
G1 X-13.074 Y-4.471 E0.48731
;WIDTH:0.4

G1 X-13.100 Y-4.445 E0.48854
;WIDTH:0.3

G1 X-13.126 Y-4.419 E0.48945
;WIDTH:0.2

G1 X-13.152 Y-4.392 E0.49004
;WIDTH:0.1

G1 X-13.179 Y-4.366 E0.49031
; INIT stop printing object patch_bed_leveling id:2 copy 0
G92 E0
G1 E-2.00000 F2400
G92 E0
; stop printing object patch_bed_leveling id:2 copy 0
M486 S-1
G1 X-93.550 Y-93.550 F12000
M140 S60 ; set bed temperature
G10 P0 S200 ; set temperature
M107
;LAYER_CHANGE
;Z:0.375
;HEIGHT:0.375
G1 Z0.375000 F12000
G1 X-84.732 Y-84.724
G1 E2.00000 F2400
;TYPE:Skirt
;WIDTH:0.55
G1 F1800
G1 X-94.510 Y-74.955 E3.05962
G1 X-95.786 Y-74.096 E3.17755
G1 X-97.239 Y-73.575 E3.29595
G1 X-98.777 Y-73.426 E3.41436
G1 X-100.297 Y-73.658 E3.53229
G1 X-101.629 Y-74.207 E3.64271
G1 X-102.803 Y-75.051 E3.75360
G1 X-112.322 Y-84.618 E4.78824
G1 X-113.098 Y-85.875 E4.90148
G1 X-113.555 Y-87.273 E5.01425
G1 X-113.672 Y-88.739 E5.12702
G1 X-113.442 Y-90.192 E5.23979
G1 X-112.862 Y-91.577 E5.35491
G1 X-111.969 Y-92.784 E5.47003
G1 X-93.469 Y-111.282 E7.47574
G1 X-92.539 Y-112.003 E7.56593
G1 X-91.491 Y-112.536 E7.65613
G1 X-90.366 Y-112.861 E7.74586
G1 X-89.195 Y-112.971 E7.83606
G1 X-88.139 Y-112.880 E7.91730
G1 X-87.114 Y-112.611 E7.99855
G1 X-86.149 Y-112.172 E8.07980
G1 X-85.278 Y-111.581 E8.16058
G1 X-75.693 Y-102.028 E9.19806
G1 X-74.816 Y-100.742 E9.31740
G1 X-74.285 Y-99.285 E9.43627
G1 X-74.131 Y-97.742 E9.55515
G1 X-74.364 Y-96.203 E9.67449
G1 X-74.943 Y-94.818 E9.78961
G1 X-75.841 Y-93.606 E9.90519
G1 X-84.679 Y-84.777 E10.86301
; INIT printing object patch_bed_leveling id:3 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.329 Y-89.427 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.7
G1 F1800
G1 X-98.603 Y-80.153 E1.32667
G1 X-106.947 Y-88.497 E2.52035
G1 X-89.203 Y-106.241 E5.05883
G1 X-80.859 Y-97.897 E6.25251
G1 X-89.276 Y-89.480 E7.45674
G1 X-89.812 Y-89.556 F12000
G92 E0
G1 E-2.00000 F2400
G1 X-106.247 Y-88.061 F12000
G1 E0.00000 F2400
;TYPE:Solid infill
;WIDTH:0.712527
G1 F1200
G1 X-88.963 Y-105.345 E2.51693
G1 X-88.525 Y-104.907 E2.58072
G1 X-105.612 Y-87.820 E5.06894
G1 X-105.174 Y-87.382 E5.13274
G1 X-88.087 Y-104.468 E7.62096
G1 X-87.649 Y-104.030 E7.68475
G1 X-104.736 Y-86.944 E10.17297
G1 X-104.298 Y-86.505 E10.23677
G1 X-87.211 Y-103.592 E12.72499
G1 X-86.773 Y-103.154 E12.78878
G1 X-103.860 Y-86.067 E15.27701
G1 X-103.422 Y-85.629 E15.34080
G1 X-86.335 Y-102.716 E17.82902
G1 X-85.897 Y-102.278 E17.89281
G1 X-102.983 Y-85.191 E20.38104
G1 X-102.545 Y-84.753 E20.44483
G1 X-85.458 Y-101.840 E22.93305
G1 X-85.020 Y-101.402 E22.99684
G1 X-102.107 Y-84.315 E25.48507
G1 X-101.669 Y-83.877 E25.54886
G1 X-84.582 Y-100.964 E28.03708
G1 X-84.144 Y-100.526 E28.10087
G1 X-101.231 Y-83.439 E30.58910
G1 X-100.793 Y-83.001 E30.65289
G1 X-83.706 Y-100.088 E33.14111
G1 X-83.268 Y-99.650 E33.20490
G1 X-100.355 Y-82.563 E35.69313
G1 X-99.917 Y-82.125 E35.75692
G1 X-82.830 Y-99.212 E38.24514
G1 X-82.392 Y-98.774 E38.30893
G1 X-99.479 Y-81.687 E40.79716
G1 X-99.041 Y-81.249 E40.86095
G1 X-81.954 Y-98.336 E43.34917
G1 X-81.516 Y-97.897 E43.41297
G1 X-98.800 Y-80.613 E45.92990
G92 E0
G1 E-2.00000 F2400
G1 X-89.140 Y-105.740 F12000
G1 E0.00000 F2400
;TYPE:Gap fill
;WIDTH:0.258091
G1 F1200
G1 X-89.203 Y-105.678 E0.00258
G1 X-106.383 Y-88.497 E0.70723
G1 X-106.414 Y-88.466 E0.70852
G1 X-106.446 Y-88.434 E0.70981
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:0.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z0.575000 F12000
G10 P0 S190 ; set temperature
M140 S55 ; set bed temperature
; INIT printing object patch_bed_leveling id:3 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.777 Y-105.794 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.52
G1 F1800
G1 X-89.124 Y-106.447 E0.03836
G1 X-80.653 Y-97.976 E0.53609
G1 X-81.306 Y-97.323 E0.57445
G1 X-89.724 Y-105.741 E1.06907
G1 X-89.294 Y-105.923 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:0.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z0.775000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.670 Y-105.795
G1 F600
G1 X-89.723 Y-105.848 E1.07218
G1 X-89.070 Y-106.501 E1.11055
G1 X-80.599 Y-98.030 E1.60828
G1 X-81.252 Y-97.377 E1.64664
G1 X-89.617 Y-105.742 E2.13814
G1 X-89.650 Y-105.868 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
M106 S255
;LAYER_CHANGE
;Z:0.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z0.975000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.562 Y-105.797
G1 F600
G1 X-89.668 Y-105.903 E2.14437
G1 X-89.015 Y-106.556 E2.18273
G1 X-80.544 Y-98.085 E2.68046
G1 X-81.197 Y-97.432 E2.71883
G1 X-89.509 Y-105.744 E3.20721
G1 X-89.523 Y-105.942 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:1.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z1.175000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.455 Y-105.798
G1 F600
G1 X-89.614 Y-105.957 E3.21656
G1 X-88.961 Y-106.610 E3.25492
G1 X-80.490 Y-98.139 E3.75265
G1 X-81.143 Y-97.486 E3.79101
G1 X-89.402 Y-105.745 E4.27628
G1 X-89.397 Y-106.015 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:1.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z1.375000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.559 Y-106.012
G1 F600
G1 X-88.907 Y-106.665 E4.31464
G1 X-80.435 Y-98.193 E4.81237
G1 X-81.088 Y-97.540 E4.85074
G1 X-89.506 Y-105.959 E5.34535
G1 X-89.077 Y-106.141 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:1.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z1.575000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.452 Y-106.013
G1 F600
G1 X-89.505 Y-106.066 E5.34847
G1 X-88.852 Y-106.719 E5.38683
G1 X-80.381 Y-98.248 E5.88456
G1 X-81.034 Y-97.595 E5.92292
G1 X-89.399 Y-105.960 E6.41442
G1 X-89.433 Y-106.085 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:1.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z1.775000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.345 Y-106.014
G1 F600
G1 X-89.451 Y-106.120 E6.42065
G1 X-88.798 Y-106.773 E6.45902
G1 X-80.327 Y-98.302 E6.95675
G1 X-80.980 Y-97.649 E6.99511
G1 X-89.292 Y-105.961 E7.48349
G1 X-89.306 Y-106.159 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:1.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z1.975000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.237 Y-106.016
G1 F600
G1 X-89.396 Y-106.175 E7.49284
G1 X-88.743 Y-106.828 E7.53121
G1 X-80.272 Y-98.357 E8.02894
G1 X-80.925 Y-97.704 E8.06730
G1 X-89.184 Y-105.963 E8.55257
G1 X-89.179 Y-106.233 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:2.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z2.175000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.342 Y-106.229
G1 F600
G1 X-88.689 Y-106.882 E8.59093
G1 X-80.218 Y-98.411 E9.08866
G1 X-80.871 Y-97.758 E9.12703
G1 X-89.289 Y-106.176 E9.62164
G1 X-88.859 Y-106.359 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:2.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z2.375000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.234 Y-106.231
G1 F600
G1 X-89.287 Y-106.284 E9.62476
G1 X-88.634 Y-106.937 E9.66312
G1 X-80.163 Y-98.466 E10.16085
G1 X-80.816 Y-97.813 E10.19922
G1 X-89.181 Y-106.178 E10.69071
G1 X-89.215 Y-106.303 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:2.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z2.575000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.127 Y-106.232
G1 F600
G1 X-89.233 Y-106.338 E10.69695
G1 X-88.580 Y-106.991 E10.73531
G1 X-80.109 Y-98.520 E11.23304
G1 X-80.762 Y-97.867 E11.27141
G1 X-89.074 Y-106.179 E11.75979
G1 X-89.088 Y-106.377 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:2.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z2.775000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.019 Y-106.234
G1 F600
G1 X-89.178 Y-106.393 E11.76914
G1 X-88.526 Y-107.046 E11.80750
G1 X-80.054 Y-98.574 E12.30523
G1 X-80.707 Y-97.922 E12.34360
G1 X-88.966 Y-106.181 E12.82887
G1 X-88.961 Y-106.451 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:2.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z2.975000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.124 Y-106.447
G1 F600
G1 X-88.576 Y-106.995 E12.86108
G1 X-80.105 Y-98.524 E13.35881
G1 X-80.653 Y-97.976 E13.39102
G1 X-89.071 Y-106.394 E13.88564
G1 X-88.641 Y-106.576 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:3.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z3.175000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-89.070 Y-106.502
G1 F600
G1 X-88.739 Y-106.832 E13.90506
G1 X-80.268 Y-98.361 E14.40279
G1 X-80.598 Y-98.030 E14.42221
G1 X-89.017 Y-106.448 E14.91683
G1 X-88.618 Y-106.622 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:3.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z3.375000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-88.962 Y-106.503
G1 F600
G1 X-89.015 Y-106.556 E14.91994
G1 X-88.902 Y-106.669 E14.92657
G1 X-80.431 Y-98.198 E15.42430
G1 X-80.544 Y-98.085 E15.43093
G1 X-88.909 Y-106.450 E15.92243
G1 X-88.943 Y-106.575 F12000
; INIT stop printing object patch_bed_leveling id:3 copy 0
;LAYER_CHANGE
;Z:3.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 Z3.575000 F12000
; INIT printing object patch_bed_leveling id:3 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:3 copy 0
M486 S3
G1 X-80.358 Y-97.903 F12000
G1 E0.00000 F2400
;TYPE:Thin wall
;WIDTH:0.1
G1 F600
G1 X-80.385 Y-97.929 E0.00014
;WIDTH:0.2

G1 X-80.411 Y-97.955 E0.00057
;WIDTH:0.3

G1 X-80.437 Y-97.982 E0.00132
;WIDTH:0.4

G1 X-80.463 Y-98.008 E0.00239
;WIDTH:0.5

G1 X-80.490 Y-98.034 E0.00387
G1 X-89.066 Y-106.610 E0.48657
G1 X-89.079 Y-106.624 E0.48731
;WIDTH:0.4

G1 X-89.105 Y-106.650 E0.48854
;WIDTH:0.3

G1 X-89.131 Y-106.676 E0.48945
;WIDTH:0.2

G1 X-89.158 Y-106.702 E0.49004
;WIDTH:0.1

G1 X-89.184 Y-106.729 E0.49031
; INIT stop printing object patch_bed_leveling id:3 copy 0
G92 E0
G1 E-2.00000 F2400
G92 E0
; stop printing object patch_bed_leveling id:3 copy 0
M486 S-1
G1 X93.550 Y93.550 F12000
M140 S60 ; set bed temperature
G10 P0 S200 ; set temperature
M107
;LAYER_CHANGE
;Z:0.375
;HEIGHT:0.375
G1 Z0.375000 F12000
G1 X102.368 Y102.376
G1 E2.00000 F2400
;TYPE:Skirt
;WIDTH:0.55
G1 F1800
G1 X92.590 Y112.145 E3.05962
G1 X91.314 Y113.004 E3.17755
G1 X89.861 Y113.525 E3.29595
G1 X88.323 Y113.674 E3.41436
G1 X86.803 Y113.442 E3.53229
G1 X85.471 Y112.893 E3.64271
G1 X84.296 Y112.049 E3.75360
G1 X74.778 Y102.482 E4.78824
G1 X74.005 Y101.231 E4.90101
G1 X73.545 Y99.827 E5.01425
G1 X73.428 Y98.361 E5.12702
G1 X73.658 Y96.908 E5.23979
G1 X74.238 Y95.523 E5.35491
G1 X75.131 Y94.316 E5.47003
G1 X93.631 Y75.818 E7.47574
G1 X94.561 Y75.097 E7.56593
G1 X95.609 Y74.564 E7.65613
G1 X96.733 Y74.239 E7.74586
G1 X97.905 Y74.129 E7.83606
G1 X98.961 Y74.220 E7.91730
G1 X99.986 Y74.489 E7.99855
G1 X100.951 Y74.928 E8.07980
G1 X101.822 Y75.519 E8.16058
G1 X111.407 Y85.072 E9.19806
G1 X112.284 Y86.358 E9.31740
G1 X112.815 Y87.815 E9.43627
G1 X112.969 Y89.358 E9.55515
G1 X112.736 Y90.897 E9.67449
G1 X112.157 Y92.282 E9.78961
G1 X111.259 Y93.494 E9.90519
G1 X102.421 Y102.323 E10.86301
; INIT printing object patch_bed_leveling id:4 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.771 Y97.673 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.7
G1 F1800
G1 X88.497 Y106.947 E1.32667
G1 X80.153 Y98.603 E2.52035
G1 X97.897 Y80.859 E5.05883
G1 X106.241 Y89.203 E6.25251
G1 X97.824 Y97.620 E7.45674
G1 X97.288 Y97.544 F12000
G92 E0
G1 E-2.00000 F2400
G1 X80.853 Y99.039 F12000
G1 E0.00000 F2400
;TYPE:Solid infill
;WIDTH:0.712527
G1 F1200
G1 X98.137 Y81.755 E2.51693
G1 X98.575 Y82.193 E2.58072
G1 X81.488 Y99.280 E5.06894
G1 X81.926 Y99.718 E5.13274
G1 X99.013 Y82.632 E7.62096
G1 X99.451 Y83.070 E7.68475
G1 X82.364 Y100.156 E10.17298
G1 X82.802 Y100.595 E10.23677
G1 X99.889 Y83.508 E12.72499
G1 X100.327 Y83.946 E12.78878
G1 X83.240 Y101.033 E15.27701
G1 X83.678 Y101.471 E15.34080
G1 X100.765 Y84.384 E17.82902
G1 X101.203 Y84.822 E17.89281
G1 X84.117 Y101.909 E20.38104
G1 X84.555 Y102.347 E20.44483
G1 X101.642 Y85.260 E22.93305
G1 X102.080 Y85.698 E22.99684
G1 X84.993 Y102.785 E25.48507
G1 X85.431 Y103.223 E25.54886
G1 X102.518 Y86.136 E28.03708
G1 X102.956 Y86.574 E28.10087
G1 X85.869 Y103.661 E30.58910
G1 X86.307 Y104.099 E30.65289
G1 X103.394 Y87.012 E33.14111
G1 X103.832 Y87.450 E33.20490
G1 X86.745 Y104.537 E35.69313
G1 X87.183 Y104.975 E35.75692
G1 X104.270 Y87.888 E38.24514
G1 X104.708 Y88.326 E38.30894
G1 X87.621 Y105.413 E40.79716
G1 X88.059 Y105.851 E40.86095
G1 X105.146 Y88.764 E43.34917
G1 X105.584 Y89.203 E43.41297
G1 X88.300 Y106.487 E45.92990
G92 E0
G1 E-2.00000 F2400
G1 X97.960 Y81.360 F12000
G1 E0.00000 F2400
;TYPE:Gap fill
;WIDTH:0.258088
G1 F1200
G1 X97.897 Y81.422 E0.00258
G1 X80.717 Y98.603 E0.70722
G1 X80.654 Y98.666 E0.70979
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:0.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z0.575000 F12000
G10 P0 S190 ; set temperature
M140 S55 ; set bed temperature
; INIT printing object patch_bed_leveling id:4 copy 0
G92 E0
G1 E-2.00000 F2400
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.323 Y81.306 F12000
G1 E0.00000 F2400
;TYPE:External perimeter
;WIDTH:0.52
G1 F1800
G1 X97.976 Y80.653 E0.03836
G1 X106.447 Y89.124 E0.53609
G1 X105.794 Y89.777 E0.57445
G1 X97.376 Y81.359 E1.06907
G1 X97.806 Y81.177 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:0.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z0.775000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.430 Y81.305
G1 F600
G1 X97.377 Y81.252 E1.07218
G1 X98.030 Y80.599 E1.11055
G1 X106.501 Y89.070 E1.60828
G1 X105.848 Y89.723 E1.64664
G1 X97.483 Y81.358 E2.13814
G1 X97.450 Y81.232 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
M106 S255
;LAYER_CHANGE
;Z:0.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z0.975000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.538 Y81.303
G1 F600
G1 X97.432 Y81.197 E2.14437
G1 X98.085 Y80.544 E2.18273
G1 X106.556 Y89.015 E2.68046
G1 X105.903 Y89.668 E2.71883
G1 X97.591 Y81.356 E3.20721
G1 X97.577 Y81.158 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:1.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z1.175000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.645 Y81.302
G1 F600
G1 X97.486 Y81.143 E3.21656
G1 X98.139 Y80.490 E3.25492
G1 X106.610 Y88.961 E3.75265
G1 X105.957 Y89.614 E3.79101
G1 X97.698 Y81.355 E4.27628
G1 X97.703 Y81.085 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:1.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z1.375000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.540 Y81.088
G1 F600
G1 X98.193 Y80.435 E4.31464
G1 X106.665 Y88.907 E4.81237
G1 X106.012 Y89.559 E4.85074
G1 X97.594 Y81.141 E5.34535
G1 X98.023 Y80.959 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:1.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z1.575000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.648 Y81.087
G1 F600
G1 X97.595 Y81.034 E5.34847
G1 X98.248 Y80.381 E5.38683
G1 X106.719 Y88.852 E5.88456
G1 X106.066 Y89.505 E5.92292
G1 X97.701 Y81.140 E6.41442
G1 X97.667 Y81.015 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:1.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z1.775000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.755 Y81.086
G1 F600
G1 X97.649 Y80.980 E6.42065
G1 X98.302 Y80.327 E6.45902
G1 X106.773 Y88.798 E6.95675
G1 X106.120 Y89.451 E6.99511
G1 X97.808 Y81.139 E7.48349
G1 X97.794 Y80.941 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:1.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z1.975000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.863 Y81.084
G1 F600
G1 X97.704 Y80.925 E7.49284
G1 X98.357 Y80.272 E7.53121
G1 X106.828 Y88.743 E8.02894
G1 X106.175 Y89.396 E8.06730
G1 X97.916 Y81.137 E8.55257
G1 X97.921 Y80.867 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:2.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z2.175000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.758 Y80.871
G1 F600
G1 X98.411 Y80.218 E8.59093
G1 X106.882 Y88.689 E9.08866
G1 X106.229 Y89.342 E9.12703
G1 X97.811 Y80.924 E9.62164
G1 X98.241 Y80.741 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:2.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z2.375000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.866 Y80.869
G1 F600
G1 X97.813 Y80.816 E9.62476
G1 X98.466 Y80.163 E9.66312
G1 X106.937 Y88.634 E10.16085
G1 X106.284 Y89.287 E10.19922
G1 X97.919 Y80.922 E10.69071
G1 X97.885 Y80.797 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:2.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z2.575000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.973 Y80.868
G1 F600
G1 X97.867 Y80.762 E10.69695
G1 X98.520 Y80.109 E10.73531
G1 X106.991 Y88.580 E11.23304
G1 X106.338 Y89.233 E11.27141
G1 X98.026 Y80.921 E11.75979
G1 X98.012 Y80.723 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:2.775
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z2.775000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X98.081 Y80.866
G1 F600
G1 X97.922 Y80.707 E11.76914
G1 X98.574 Y80.054 E11.80750
G1 X107.046 Y88.526 E12.30523
G1 X106.393 Y89.178 E12.34360
G1 X98.134 Y80.919 E12.82887
G1 X98.139 Y80.649 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:2.975
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z2.975000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.976 Y80.653
G1 F600
G1 X98.524 Y80.105 E12.86108
G1 X106.995 Y88.576 E13.35881
G1 X106.447 Y89.124 E13.39102
G1 X98.029 Y80.706 E13.88564
G1 X98.459 Y80.523 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:3.175
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z3.175000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X98.030 Y80.598
G1 F600
G1 X98.361 Y80.268 E13.90506
G1 X106.832 Y88.739 E14.40279
G1 X106.502 Y89.070 E14.42221
G1 X98.083 Y80.652 E14.91683
G1 X98.482 Y80.477 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:3.375
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z3.375000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X98.138 Y80.597
G1 F600
G1 X98.085 Y80.544 E14.91994
G1 X98.198 Y80.431 E14.92657
G1 X106.669 Y88.902 E15.42430
G1 X106.556 Y89.015 E15.43093
G1 X98.191 Y80.650 E15.92243
G1 X98.157 Y80.525 F12000
; INIT stop printing object patch_bed_leveling id:4 copy 0
;LAYER_CHANGE
;Z:3.575
;HEIGHT:0.2
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
G1 Z3.575000 F12000
; INIT printing object patch_bed_leveling id:4 copy 0
; printing object patch_bed_leveling id:4 copy 0
M486 S4
G1 X97.903 Y80.358
;TYPE:Thin wall
;WIDTH:0.1
G1 F600
G1 X97.929 Y80.385 E15.92257
;WIDTH:0.2

G1 X97.955 Y80.411 E15.92300
;WIDTH:0.3

G1 X97.982 Y80.437 E15.92375
;WIDTH:0.4

G1 X98.008 Y80.463 E15.92482
;WIDTH:0.5

G1 X98.034 Y80.490 E15.92630
G1 X106.610 Y89.066 E16.40899
G1 X106.624 Y89.079 E16.40973
;WIDTH:0.4

G1 X106.650 Y89.105 E16.41097
;WIDTH:0.3

G1 X106.676 Y89.131 E16.41188
;WIDTH:0.2

G1 X106.702 Y89.158 E16.41247
;WIDTH:0.1

G1 X106.729 Y89.184 E16.41274
; INIT stop printing object patch_bed_leveling id:4 copy 0
G92 E0
G1 E-2.00000 F2400
; stop printing object patch_bed_leveling id:4 copy 0
M486 S-1
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M0
; filament used [mm] = 396.86
; filament used [cm3] = 0.91
; filament used [g] = 1.14
; filament cost = 0.04
; total filament used [g] = 1.14
; total filament cost = 0.04
; estimated printing time (normal mode) = 6m 0s

; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 149.429x13.0734,147.721x26.0472,144.889x38.8229,140.954x51.303,135.946x63.3927,129.904x75,122.873x86.0365,114.907x96.4181,106.066x106.066,96.4181x114.907,86.0365x122.873,75x129.904,63.3927x135.946,51.303x140.954,38.8229x144.889,26.0472x147.721,13.0734x149.429,9.18485e-15x150,-13.0734x149.429,-26.0472x147.721,-38.8229x144.889,-51.303x140.954,-63.3927x135.946,-75x129.904,-86.0365x122.873,-96.4181x114.907,-106.066x106.066,-114.907x96.4181,-122.873x86.0365,-129.904x75,-135.946x63.3927,-140.954x51.303,-144.889x38.8229,-147.721x26.0472,-149.429x13.0734,-150x1.83697e-14,-149.429x-13.0734,-147.721x-26.0472,-144.889x-38.8229,-140.954x-51.303,-135.946x-63.3927,-129.904x-75,-122.873x-86.0365,-114.907x-96.4181,-106.066x-106.066,-96.4181x-114.907,-86.0365x-122.873,-75x-129.904,-63.3927x-135.946,-51.303x-140.954,-38.8229x-144.889,-26.0472x-147.721,-13.0734x-149.429,-2.75546e-14x-150,13.0734x-149.429,26.0472x-147.721,38.8229x-144.889,51.303x-140.954,63.3927x-135.946,75x-129.904,86.0365x-122.873,96.4181x-114.907,106.066x-106.066,114.907x-96.4181,122.873x-86.0365,129.904x-75,135.946x-63.3927,140.954x-51.303,144.889x-38.8229,147.721x-26.0472,149.429x-13.0734,150x-3.67394e-14
; bed_temperature = 55,55
; before_layer_gcode = 
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 100%
; bridge_overlap = 100%
; bridge_speed = 60
; bridge_speed_internal = 150%
; bridged_infill_margin = 200%
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_offset = 0
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0,0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 1
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling = 1,1
; cooling_tube_length = 5
; cooling_tube_retraction = 45
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 3,3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n";"; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M0
; enforce_full_fill_volume = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 100%
; external_perimeter_extrusion_width = 
; external_perimeter_fan_speed = -1,-1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ;
; extruder_fan_offset = 0%,0%
; extruder_offset = 0x0,0x0
; extruder_temperature_offset = 0,0
; extrusion_axis = E
; extrusion_multiplier = 1,1
; extrusion_spacing = 105%
; extrusion_width = 
; fan_always_on = 1,1
; fan_below_layer_time = 60,60
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = 
; filament_colour = #46484A;#46484A
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cooling_zone_pause = 0,0
; filament_cost = 37,37
; filament_density = 1.25,1.25
; filament_diameter = 1.71,1.71
; filament_dip_extraction_speed = 70,70
; filament_dip_insertion_speed = 33,33
; filament_enable_toolchange_part_fan = 0,0
; filament_enable_toolchange_temp = 0,0
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_speed = 0,0
; filament_max_volumetric_speed = 0,0
; filament_max_wipe_tower_speed = 0,0
; filament_melt_zone_pause = 0,0
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = ;
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Atomic PLA - Cosmic Graphite";"Atomic PLA - Cosmic Graphite"
; filament_shrink = 100%,100%
; filament_skinnydip_distance = 31,31
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_toolchange_part_fan_speed = 50,50
; filament_toolchange_temp = 200,200
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_use_fast_skinnydip = 0,0
; filament_use_skinnydip = 0,0
; filament_vendor = (Unknown)
; filament_wipe_advanced_pigment = 0.5,0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 18%
; fill_pattern = gyroid
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 0
; first_layer_bed_temperature = 60,60
; first_layer_extrusion_spacing = 140%
; first_layer_extrusion_width = 
; first_layer_flow_ratio = 100%
; first_layer_height = 75%
; first_layer_infill_speed = 30
; first_layer_size_compensation = 0
; first_layer_speed = 30
; first_layer_temperature = 200,200
; full_fan_speed_layer = 0,0
; gap_fill = 1
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 1
; gcode_precision_e = 5,5
; gcode_precision_xyz = 3
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 0
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 1
; infill_dense_algo = autoenlarged
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 100%
; infill_extrusion_width = 
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 500
; max_print_speed = 80
; max_speed_reduction = 90%,90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 35,35
; min_layer_height = 0.07,0.07
; min_length = 0.035
; min_print_speed = 10,10
; min_skirt_length = 0
; min_width_top_surface = 200%
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes = 
; nozzle_diameter = 0.5,0.5
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}.gcode
; over_bridge_flow_ratio = 100%
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 55%
; parking_pos_retraction = 107
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 105%
; perimeter_extrusion_width = 
; perimeter_loop = 1
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = Cabinet Artemis
; post_process = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = Default-2020-09-20
; print_temperature = 0
; printer_model = 
; printer_notes = 
; printer_settings_id = SeeMeCNC Artemis 300
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_layers = 0
; remaining_times = 0
; resolution = 0.002
; retract_before_travel = 2,2
; retract_before_wipe = 0%,0%
; retract_layer_change = 0,0
; retract_length = 2,2
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 0,0
; retract_lift_first_layer = 0,0
; retract_lift_top = "All surfaces";"All surfaces"
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; seam_angle_cost = 100%
; seam_position = cost
; seam_travel_cost = 100%
; silent_mode = 1
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_extrusion_width = 110%
; skirt_height = 1
; skirts = 1
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 5,5
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 15
; solid_fill_pattern = rectilineargapfill
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 105%
; solid_infill_extrusion_width = 
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n";"; Filament gcode\n"
; start_gcode = ; Call the print start macro and pass in first layer temp and bed temp.\n; TODO: when we are using the right-side extruder, start there instead of running this against the wrong one\nM140 S0\nM568 P0 R0 S0 A0\nM98 P"0:/macros/sys/start_print.g" T[first_layer_temperature] B[first_layer_bed_temperature]; call print start macro (handles loading filament, priming nozzle, etc.\n
; start_gcode_manual = 0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance_bottom = 0.2
; support_material_contact_distance_top = 0.2
; support_material_contact_distance_type = plane
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 100%
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_solid_first_layer = 0
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 190,190
; template_custom_gcode = 
; thin_perimeters = 1
; thin_perimeters_all = 0
; thin_walls = 1
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 30
; threads = 4
; thumbnails = 0x0,0x0
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_with_bed = 1
; time_estimation_compensation = 100%
; tool_name = "Left Extruder";"Right Extruder"
; toolchange_gcode = ; TOOL CHANGE\n; TODO: how do we make this play nice with a wipe tower, if present?\nG92 E0\nG1 E-5\nG1 X0 Y130 F20000 ; Move toolhead away\nG92 E0\nG1 E-155 F5000 ; Retract filament out of Y\nG92 E0\n\nT[next_extruder] P0 ; Change tools\nG92 E0\nG1 E160 F5000 ; Extrude new filament\nG92 E0\n\nM18 E[previous_extruder] ; Disable previous extruder motor
; top_fan_speed = -1,-1
; top_fill_pattern = monotonic
; top_infill_extrusion_spacing = 100%
; top_infill_extrusion_width = 
; top_solid_infill_speed = 15
; top_solid_layers = 4
; top_solid_min_thickness = 0
; travel_speed = 200
; travel_speed_z = 200
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim = 150%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.005
